export const GET_DEPLOYMENTS = "GET_DEPLOYMENTS";
export const GET_DEPLOYMENT_ERROR = "GET_DEPLOYMENT_ERROR";

export const CREATE_DEPLOYMENT = "CREATE_DEPLOYMENT";
export const CREATE_DEPLOYMENT_ERROR = "CREATE_DEPLOYMENT_ERROR";

export const DELETE_DEPLOYMENT = "DELETE_DEPLOYMENT";
export const DELETE_DEPLOYMENT_ERROR = "DELETE_DEPLOYMENT_ERROR";
